apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/demo.yaml
  - infra/metallb.yaml
  - infra/ingress-nginx.yaml
  - infra/metrics-server.yaml
  - infra/cert-manager.yaml
  - infra/cert-manager-issuers.yaml
  - infra/nfs-provisioner.yaml
  - apps/rabbitmq.yaml
