apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "83.6.0"
    helm:
      releaseName: monitoring
      values: |
        grafana:
          enabled: true
          adminUser: admin
          adminPassword: admin123456

          service:
            type: ClusterIP

          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: local-ca
            hosts:
              - grafana.local
            tls:
              - secretName: grafana-local-tls
                hosts:
                  - grafana.local

          persistence:
            enabled: true
            storageClassName: nfs-client
            size: 1Gi

        prometheus:
          prometheusSpec:
            retention: 3d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-client
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 4Gi

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-client
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: false

        kubeScheduler:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
