replicaCount: 1

auth:
  username: admin
  password: admin123
  erlangCookie: "home-lab-rabbitmq-cookie"

clustering:
  enabled: false

persistence:
  enabled: true
  storageClass: nfs-client
  size: 2Gi

resourcesPreset: "none"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

metrics:
  enabled: false

volumePermissions:
  enabled: false
